server:
  port: 8080


spring:
  mail:
    #smtp服务主机，163邮箱是smtp.163.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    #编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 1186939108@qq.com
    #授权码
    password: nfhtzsvocpbmibia
    test-connection: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: email
    port: 465


